import type { AccessEntry } from "$lib/types/app-types"

export const ACCESS_TYPE_DISPLAY_NAMES: Record<AccessEntry["type"], string> = {
  "AUTOMATISK-KLASSE-TILGANG": "Klasselærer (InSchool) for",
  "AUTOMATISK-KONTAKTLÆRERGRUPPE-TILGANG": "Kontaktlærer (InSchool) for",
  "AUTOMATISK-UNDERVISNINGSGRUPPE-TILGANG": "Faglærer (InSchool) for",
  "MANUELL-OPPRETT-MANUELL-ELEV-TILGANG": "Opprett manuelle elever",
  "MANUELL-ELEV-TILGANG": "Elevtilgang",
  "MANUELL-KLASSE-TILGANG": "Klassetilgang",
  "MANUELL-SKOLELEDER-TILGANG": "Skoleleder",
  "MANUELL-PROGRAMOMRÅDE-TILGANG": "Programområde-tilgang"
}

export const ACCESS_TYPE_PRIORITY: Record<AccessEntry["type"], number> = {
  "MANUELL-SKOLELEDER-TILGANG": 1,
  "MANUELL-ELEV-TILGANG": 2,
  "MANUELL-KLASSE-TILGANG": 2,
  "MANUELL-PROGRAMOMRÅDE-TILGANG": 2,
  "AUTOMATISK-KONTAKTLÆRERGRUPPE-TILGANG": 2,
  "AUTOMATISK-KLASSE-TILGANG": 3,
  "AUTOMATISK-UNDERVISNINGSGRUPPE-TILGANG": 4,
  "MANUELL-OPPRETT-MANUELL-ELEV-TILGANG": 100
}
